$axure.loadCurrentPage({
  "url":"mobile.html",
  "generationDate":new Date(1397981600713.54),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"16e933ff5a2b42bbb0b9f1492c6bf097",
    "type":"Axure:Page",
    "name":"Mobile",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f41bac135a74430fbaacd41a2d1c43f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":320,
              "height":520},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6c1b8bab76d4aa79466bb9f7faa6577",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":320,
                  "height":520},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mobile/u0.png"}},
{
          "id":"2e15371647fd443688157f97c01c40c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "lineSpacing":"26px",
            "location":{
              "x":20,
              "y":920},
            "size":{
              "width":280,
              "height":650}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f29b3a75080b469ca6505e7fa75ca3a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "lineSpacing":"26px",
                "location":{
                  "x":20,
                  "y":920},
                "size":{
                  "width":280,
                  "height":650}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4838de867df74bd3b4b6c5aed50949a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":60,
              "y":660},
            "size":{
              "width":200,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5513a4064d0b4176900c8620cb267be3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":60,
                  "y":660},
                "size":{
                  "width":200,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"b96cf30771ac49359818c7c12169035d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "lineSpacing":"48px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":0,
              "y":1680},
            "size":{
              "width":320,
              "height":600},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcae03803b6040a7a4210507dab7823e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "lineSpacing":"48px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":1680},
                "size":{
                  "width":320,
                  "height":600},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mobile/u6.png"}},
{
          "id":"d8f1246b21994541b187f0fcb2721281",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "horizontalAlignment":"center",
            "lineSpacing":"48px",
            "location":{
              "x":5,
              "y":2421},
            "size":{
              "width":310,
              "height":139}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30445d2cdb134909b529a4f196eb7cc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "horizontalAlignment":"center",
                "lineSpacing":"48px",
                "location":{
                  "x":5,
                  "y":2421},
                "size":{
                  "width":310,
                  "height":139}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"20f04da3549b4eddb2075ae02e9aa07d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":2583},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c4a280c66f54e1796d7696843eac86c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":2583},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mobile/u10.png"}},
{
          "id":"fa40dd49dd7c421c9f3fd6a84929ee5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "lineSpacing":"18px",
            "location":{
              "x":10,
              "y":2630},
            "size":{
              "width":80,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1af23d92b667479e9368f260015a3db6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "lineSpacing":"18px",
                "location":{
                  "x":10,
                  "y":2630},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6dd6e0e049249e88764f42ca507e312",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":2583},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2de81ea9a7474939864f618602613f06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":2583},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mobile/u10.png"}},
{
          "id":"a9945baaee554b5ba1861980bb4b3bf5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "lineSpacing":"18px",
            "location":{
              "x":100,
              "y":2630},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab0beed6663945ca9096d8a0310fc31a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "lineSpacing":"18px",
                "location":{
                  "x":100,
                  "y":2630},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d93e72721c2749d1840c486d1c896d83",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":2583},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91145cc2cc3d49fa84f4551b7c351577",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":2583},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/mobile/u10.png"}},
{
          "id":"be2ce3c1c06643fdaa33b730b69769ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "lineSpacing":"18px",
            "location":{
              "x":230,
              "y":2630},
            "size":{
              "width":80,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e667de5bde914f9791d77836af0d5ebe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "lineSpacing":"18px",
                "location":{
                  "x":230,
                  "y":2630},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f41bac135a74430fbaacd41a2d1c43f9":{
      "scriptId":"u0"},
    "d6c1b8bab76d4aa79466bb9f7faa6577":{
      "scriptId":"u1"},
    "2e15371647fd443688157f97c01c40c3":{
      "scriptId":"u2"},
    "f29b3a75080b469ca6505e7fa75ca3a9":{
      "scriptId":"u3"},
    "4838de867df74bd3b4b6c5aed50949a1":{
      "scriptId":"u4"},
    "5513a4064d0b4176900c8620cb267be3":{
      "scriptId":"u5"},
    "b96cf30771ac49359818c7c12169035d":{
      "scriptId":"u6"},
    "dcae03803b6040a7a4210507dab7823e":{
      "scriptId":"u7"},
    "d8f1246b21994541b187f0fcb2721281":{
      "scriptId":"u8"},
    "30445d2cdb134909b529a4f196eb7cc8":{
      "scriptId":"u9"},
    "20f04da3549b4eddb2075ae02e9aa07d":{
      "scriptId":"u10"},
    "0c4a280c66f54e1796d7696843eac86c":{
      "scriptId":"u11"},
    "fa40dd49dd7c421c9f3fd6a84929ee5d":{
      "scriptId":"u12"},
    "1af23d92b667479e9368f260015a3db6":{
      "scriptId":"u13"},
    "e6dd6e0e049249e88764f42ca507e312":{
      "scriptId":"u14"},
    "2de81ea9a7474939864f618602613f06":{
      "scriptId":"u15"},
    "a9945baaee554b5ba1861980bb4b3bf5":{
      "scriptId":"u16"},
    "ab0beed6663945ca9096d8a0310fc31a":{
      "scriptId":"u17"},
    "d93e72721c2749d1840c486d1c896d83":{
      "scriptId":"u18"},
    "91145cc2cc3d49fa84f4551b7c351577":{
      "scriptId":"u19"},
    "be2ce3c1c06643fdaa33b730b69769ad":{
      "scriptId":"u20"},
    "e667de5bde914f9791d77836af0d5ebe":{
      "scriptId":"u21"}}});